---
- name: Assemble all the configuration bits
  assemble:
    src: "{{ conf_dir }}/"
    dest: "{{ conf_dir }}/assembled.conf"
  check_mode: no
  changed_when: false

- name: NAPALM - Commit check config
  napalm_install_config:
    provider: "{{napalm_provider }}"
    config_file: "{{ conf_dir }}/assembled.conf"
    commit_changes: "{{ not ansible_check_mode }}"
    replace_config: false
    get_diffs: true
    diff_file: "{{ diff_dir }}/config.diff"
    archive_file: "{{ conf_dir }}/backup.conf"
    timeout: "{{ timeout }}"
    optional_args:
      ignore_warning: ['statement not found', 'statement has no contents; ignored']
  check_mode: yes
  no_log: "{{nolog}}"
  changed_when: false

- name: Get diff
  shell: cat {{ diff_dir }}/config.diff > /dev/stdout
  register: diffresult
  check_mode: no
  changed_when: false

- name: Print diff
  debug:
    msg: "{{diffresult.stdout_lines}}"
  check_mode: no
  changed_when: not ansible_check_mode and diffresult.stdout_lines | length > 0

  #- name: Pause
  #  run_once: false
  #  pause:
  #    seconds: "{{ pause }}"
  #  when: not ansible_check_mode and diffresult.stdout_lines | length > 0

- name: NAPALM - Deploy config
  napalm_install_config:
    provider: "{{napalm_provider }}"
    config_file: "{{ conf_dir }}/assembled.conf"
    commit_changes: true
    replace_config: false
    get_diffs: false
    timeout: "{{ timeout }}"
    optional_args:
      ignore_warning: ['statement not found', 'statement has no contents; ignored']
  no_log: "{{nolog}}"
  changed_when: false
  when: not ansible_check_mode and diffresult.stdout_lines | length > 0
