---
- name: Assemble all the configuration bits
  assemble:
    src: "{{ conf_dir }}/"
    dest: "{{ conf_dir }}/assembled.conf"
  check_mode: no
  changed_when: False

- name: Show configuration changes
  eos_config:
    provider: "{{ eos_provider }}"
    src: "{{ conf_dir }}/assembled.conf"
    backup: no
    replace: config
    diff_against: session
    save_when: never
  check_mode: yes
  register: result
  changed_when: result is defined and result.diff is defined and result.diff.prepared is defined and result.diff.prepared != "\n"

  #- debug:
  #    var: result

- name: Give time to cancel changes
  run_once: true
  delegate_to: localhost
  pause:
    seconds: "{{ pause }}"
  when: not ansible_check_mode and result.diff.prepared != "\n"

- name: Apply configuration changes
  eos_config:
    provider: "{{ eos_provider }}"
    src: "{{ conf_dir }}/assembled.conf"
    backup: no
    replace: config
    diff_against: session
    save_when: modified
  when: not ansible_check_mode and result.diff.prepared != "\n"
  changed_when: false

