---

- name: Assemble all the configuration bits
  assemble:
    src: "{{ conf_dir }}/"
    dest: "{{ conf_dir }}/assembled.conf"
  check_mode: no
  changed_when: False
  tags: always

- name: Get candidate configuration
  napalm_install_config:
    provider: "{{ napalm_provider }}"
    config_file: "{{ conf_dir }}/assembled.conf"
    archive_file: "{{ conf_dir }}/running.conf"
    candidate_file: "{{ conf_dir}}/candidate.conf"
    commit_changes: false
    replace_config: false
    get_diffs: true
    diff_file: "{{ conf_dir }}/diff.conf"
  check_mode: true
  register: result
  diff: false
  changed_when: false
  tags: always

- name: Show changes
  copy:
    src: "{{ conf_dir }}/candidate.conf"
    dest: "{{ conf_dir }}/running.conf"
  check_mode: yes
  diff: yes
  changed_when: not result.msg == ""
  tags: always

- name: Pause
  pause:
    prompt: Last chance to cancel changes
    seconds: 60
  when: not ansible_check_mode and not result.msg == ""
  tags: always


- name: Install configuration
  napalm_install_config:
    provider: "{{ napalm_provider }}"
    config_file: "{{ conf_dir }}/assembled.conf"
    commit_changes: true
    replace_config: false
    get_diffs: false
  check_mode: false
  diff: false
  changed_when: true
  when: not ansible_check_mode and not result.msg == ""
  tags: always
