---

#- name: EOS - Show changes
#  eos_config:
#    provider: "{{ eos_provider }}"
#    src: "{{ conf_dir }}/assembled.conf"
#    match: none
#    backup: no
#    diff_against: session
#    save_when: never
#  check_mode: true
#  register: result
#  diff: true
#  changed_when: result.diff is defined
#  tags: always

- name: EOS - Get candidate configuration
  napalm_install_config:
    provider: "{{ napalm_provider }}"
    config_file: "{{ conf_dir }}/assembled.conf"
    archive_file: "{{ conf_dir }}/running.conf"
    candidate_file: "{{ conf_dir}}/candidate.conf"
    commit_changes: false
    replace_config: false
    get_diffs: true
    diff_file: "{{ conf_dir }}/diff.conf"
  check_mode: true
  register: result
  diff: false
  changed_when: false
  #changed_when: result.diff is defined
  tags: always

- debug:
    var: result

- name: EOS - Show changes
  copy:
    src: "{{ conf_dir }}/candidate.conf"
    dest: "{{ conf_dir }}/running.conf"
  check_mode: yes
  diff: yes
  changed_when: result.msg is defined
  tags: always
