---

- name: Generate new banner
  template:
    src: "{{ ansible_network_os }}/banner.j2"
    dest: "{{ conf_dir}}/banner.conf"
  check_mode: no
  changed_when: false

- name: Update login banner
  juniper_junos_config:
    provider: "{{ junos_provider }}"
    src: "{{ conf_dir}}/banner.conf"
    format: "text"
    load: 'merge'
    check: false
    comment: 'Updating banner after software upgrade'
