---

- name: Install new image
  juniper_junos_software:
    provider: "{{ junos_provider }}"
    remote_package: "{{ swi_url}}"
    reboot: yes
    logfile: "{{ conf_dir }}/software.log"
    all_re: yes
    cleanfs: yes
    force_host: yes
    reboot_pause: 300
  ignore_errors: yes
  when: perform_upgrade

- name: Wait for the switch to come back online
  wait_for:
    host: "{{ inventory_hostname }}"
    delay: "{{ install_pause }}"
    port: 22
    timeout: "{{ reboot_timer }}"
  when: perform_upgrade
  ignore_errors: yes

- pause:
    seconds: "{{ install_pause }}"
  when: perform_upgrade

- name: Gather show version facts
  include_role:
    name: facts
  when: perform_upgrade

- name: Check new Junos version
  assert:
    that:
      - "'{{ target_version }}' == '{{ napalm_os_version }}'"
    msg: "Upgrade failed. New version is {{ napalm_os_version }} instead of {{ target_version }}"
  when: perform_upgrade

