---

- set_fact:
    rsi_file: "flash:show_tech_support_{{ inventory_hostname }}_{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}.txt"

- name: Get support information
  eos_command:
    provider: "{{ eos_provider }}"
    commands:
      - command: "show tech-support > {{ rsi_file }}"
  changed_when: false

- name: Copy support information file to remote location
  eos_command:
    provider: "{{ eos_provider }}"
    commands:
      - "enable"
      - "routing-context vrf {{ management.vrf_lite | default('default') }}"
      - "copy {{ rsi_file}} {{ uri_remote_location }}"
  changed_when: false

- name: Delete local file
  eos_command:
    provider: "{{ eos_provider }}"
    commands:
      - "delete {{ rsi_file }}"
  changed_when: false

