---

- name: Facts
  include_role:
    name: facts
  when: perform_upgrade

- name: Update login banner
  eos_banner:
    provider: "{{ eos_provider }}"
    banner: login
    text: "{{ banner }}"
  when: perform_upgrade and banner is defined

- name: Update MOTD
  eos_banner:
    provider: "{{ eos_provider }}"
    banner: motd
    text: "{{ motd }}"
  when: perform_upgrade and motd is defined
