---
# Pedro Antunes
# pedro.antunes@eplus.com
# ------------------------------------------------------------#
- name: Backup
  hosts:
    - all
  connection: local
  gather_facts: no
  environment:
    PYTHONHTTPSVERIFY: 0
  vars:
    config_file:  "configs/{{ inventory_hostname }}.{{ ansible_network_os }}"
  tasks:
    - name: Backup running configuration
      backup:
        dev_os : "{{ ansible_network_os }}"
        model : "{{ model }}"
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        config_file: "{{ config_file }}"
      diff: true
