---

- name: Configure network devices
  hosts:
    - testswitch
    - testrouter
    - testfirewall
  connection: local
  gather_facts: no
  vars:
    config_file: "configs/{{ inventory_hostname }}.{{ ansible_network_os }}"

  tasks:

    - name: Push config
      config:
        dev_os : "{{ ansible_network_os }}"
        model : "{{ ansible_network_os }}"
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        config_file: "{{ config_file }}"
        banner: "{{ banner }}"
        motd: "{{ motd }}"
      diff: true
