---

- name: Install management configuration
  hosts:
    - infrastructurenetwork
    - testswitch
    - testrouter
    - testfirewall
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  vars:
    main_conf_dir: "{{ playbook_dir }}/.config"

  pre_tasks:
    - name: Set some facts
      set_fact:
        conf_dir: "{{ main_conf_dir }}/{{ inventory_hostname }}"
      changed_when: false
      check_mode: false
      tags: always
    - name: Clear folders
      file:
        path: "{{ item }}"
        state: absent
      run_once: true
      with_items:
        - "{{ main_conf_dir }}"
      changed_when: false
      check_mode: false
      tags: always
    - name: Recreate folders
      file:
        path: "{{ item }}"
        state: directory
        mode: 02775
      with_items:
        - "{{ conf_dir }}"
      changed_when: false
      check_mode: false
      tags: always


  tasks:
    - name: Facts
      include_role:
        name: facts
      tags:
        - never
        - facts

    - name: Management
      include_role:
        name: management
      tags: always

    - name: Raw commands
      include_role:
        name: raw
      when: raw is defined
      tags: always

    - name: Deploy
      include_role:
        name: deploy
      tags: always
