---

- name: Install new software image
  hosts:
    - test-switch
    - test-router
    - test-firewall
  roles:
    - Juniper.junos
  connection: local
  gather_facts: false
  vars:
    main_conf_dir: "{{ playbook_dir }}/.config"

  pre_tasks:
    - name: Clear folders
      file:
        path: "{{ playbook_dir }}/.config"
        state: absent
      run_once: true
      changed_when: false
      check_mode: false
      ignore_errors: true
    - name: Define working directories
      set_fact:
        conf_dir: "{{ main_conf_dir }}/{{ inventory_hostname }}"
      changed_when: false
      check_mode: false
    - name: Recreate folders
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ conf_dir }}"
      changed_when: false
      check_mode: false

  tasks:
    - name: Upgrade
      include_role:
        name: image
      when: image_url is defined
