---

- name: Junos - Install new configuration 
  juniper_junos_config:
    check: true
    commit: true
    format: text
    load: replace
    retrieve: candidate
    return_output: true
    src: "{{ conf_dir }}/assembled.conf"
    provider: "{{ junos_provider }}"
  diff: false
  when: not ansible_check_mode and result.diff is defined
  tags: always

